export const pagesRoutes = [
  ["v-01560935","/timeline/",{"title":""},["/timeline/index.html"]],
  ["v-e1e3da16","/posts/",{"title":""},["/posts/index.html"]],
  ["v-53355ebb","/friendship-link/",{"title":""},["/friendship-link/index.html"]],
  ["v-5b440fe2","/categories/Japanese/1/",{"title":""},["/categories/Japanese/1/index.html"]],
  ["v-38ababda","/categories/History/1/",{"title":""},["/categories/History/1/index.html"]],
  ["v-16736bd8","/categories/reco/1/",{"title":""},["/categories/reco/1/index.html"]],
  ["v-6bcafc81","/tags/Literature%20notes/1/",{"title":""},["/tags/Literature notes/1/","/tags/Literature%20notes/1/index.html"]],
  ["v-3759c544","/tags/Inbox/1/",{"title":""},["/tags/Inbox/1/index.html"]],
  ["v-03d52fd3","/posts/1/",{"title":""},["/posts/1/index.html"]],
  ["v-8daa1a0e","/",{"title":""},["/index.html","/README.md"]],
  ["v-bb025cf6","/docs/about/1.html",{"title":"About this wiki"},["/docs/about/1","/docs/about/1.md"]],
  ["v-6328d5a6","/docs/wiki's_project/1.html",{"title":"项目管理"},["/docs/wiki's_project/1","/docs/wiki's_project/1.md"]],
  ["v-64ddae45","/docs/wiki's_project/2.html",{"title":"范围报告书"},["/docs/wiki's_project/2","/docs/wiki's_project/2.md"]],
  ["v-669286e4","/docs/wiki's_project/3.html",{"title":"WBS 工作分解结构表"},["/docs/wiki's_project/3","/docs/wiki's_project/3.md"]],
  ["v-e3d29188","/docs/wiki's_project/MBP.html",{"title":"项目管理"},["/docs/wiki's_project/MBP","/docs/wiki's_project/MBP.md"]],
  ["v-11f7c3b9","/docs/wiki's_project/Project_Scope_Statement.html",{"title":"项目范围说明书"},["/docs/wiki's_project/Project_Scope_Statement","/docs/wiki's_project/Project_Scope_Statement.md"]],
  ["v-75e18ae6","/docs/wiki's_project/Requirements_Document.html",{"title":"需求文件"},["/docs/wiki's_project/Requirements_Document","/docs/wiki's_project/Requirements_Document.md"]],
  ["v-37af1565","/docs/wiki's_project/Requirements_Management_Plan.html",{"title":"需求管理计划"},["/docs/wiki's_project/Requirements_Management_Plan","/docs/wiki's_project/Requirements_Management_Plan.md"]],
  ["v-33f16162","/docs/wiki's_project/Requirements_Traceability_Matrix.html",{"title":"需求跟踪矩阵"},["/docs/wiki's_project/Requirements_Traceability_Matrix","/docs/wiki's_project/Requirements_Traceability_Matrix.md"]],
  ["v-44061dcb","/docs/wiki's_project/mba.html",{"title":"项目管理计划"},["/docs/wiki's_project/mba","/docs/wiki's_project/mba.md"]],
  ["v-4d8f272e","/docs/wiki's_project/project_charte.html",{"title":"项目章程"},["/docs/wiki's_project/project_charte","/docs/wiki's_project/project_charte.md"]],
  ["v-6bb1ef33","/blogs/other/guide.html",{"title":"vuepress-theme-reco"},["/blogs/other/guide","/blogs/other/guide.md"]],
  ["v-7991f123","/docs/JP/202307/1.html",{"title":"first note of genki"},["/docs/JP/202307/1","/docs/JP/202307/1.md"]],
  ["v-4058ef08","/blogs/Literature%20notes/JP/1.html",{"title":"first note of genki"},["/blogs/Literature notes/JP/1.html","/blogs/Literature%20notes/JP/1","/blogs/Literature notes/JP/1.md","/blogs/Literature%20notes/JP/1.md"]],
  ["v-0e5dad67","/blogs/Inbox/HT/5.html",{"title":"class 5"},["/blogs/Inbox/HT/5","/blogs/Inbox/HT/5.md"]],
  ["v-10128606","/blogs/Inbox/HT/6.html",{"title":"class 6"},["/blogs/Inbox/HT/6","/blogs/Inbox/HT/6.md"]],
  ["v-11c75ea5","/blogs/Inbox/HT/7.html",{"title":"class 7"},["/blogs/Inbox/HT/7","/blogs/Inbox/HT/7.md"]],
  ["v-137c3744","/blogs/Inbox/HT/8.html",{"title":"class 8"},["/blogs/Inbox/HT/8","/blogs/Inbox/HT/8.md"]],
  ["v-5f86c8ac","/docs/Inbox/HT/G1/5.html",{"title":"第5课 三国两晋南北朝的政权更迭与民族交融"},["/docs/Inbox/HT/G1/5","/docs/Inbox/HT/G1/5.md"]],
  ["v-5c1d176e","/docs/Inbox/HT/G1/6.html",{"title":""},["/docs/Inbox/HT/G1/6","/docs/Inbox/HT/G1/6.md"]],
  ["v-58b36630","/docs/Inbox/HT/G1/7.html",{"title":"第七课 隋唐制度的变化与创新 教学设计"},["/docs/Inbox/HT/G1/7","/docs/Inbox/HT/G1/7.md"]],
  ["v-5549b4f2","/docs/Inbox/HT/G1/8.html",{"title":"8　三国至隋唐的文化"},["/docs/Inbox/HT/G1/8","/docs/Inbox/HT/G1/8.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
