export const pagesRoutes = [
  ["v-01560935","/timeline/",{"title":""},["/timeline/index.html"]],
  ["v-e1e3da16","/posts/",{"title":""},["/posts/index.html"]],
  ["v-53355ebb","/friendship-link/",{"title":""},["/friendship-link/index.html"]],
  ["v-38ababda","/categories/History/1/",{"title":""},["/categories/History/1/index.html"]],
  ["v-5b440fe2","/categories/Japanese/1/",{"title":""},["/categories/Japanese/1/index.html"]],
  ["v-16736bd8","/categories/reco/1/",{"title":""},["/categories/reco/1/index.html"]],
  ["v-3759c544","/tags/Inbox/1/",{"title":""},["/tags/Inbox/1/index.html"]],
  ["v-6bcafc81","/tags/Literature%20notes/1/",{"title":""},["/tags/Literature notes/1/","/tags/Literature%20notes/1/index.html"]],
  ["v-03d52fd3","/posts/1/",{"title":""},["/posts/1/index.html"]],
  ["v-8daa1a0e","/",{"title":""},["/index.html","/README.md"]],
  ["v-6bb1ef33","/blogs/other/guide.html",{"title":"vuepress-theme-reco"},["/blogs/other/guide","/blogs/other/guide.md"]],
  ["v-4ec7e05c","/docs/LN/LN1.html",{"title":"first note of genki"},["/docs/LN/LN1","/docs/LN/LN1.md"]],
  ["v-1f3e6ab7","/docs/MBP/1.html",{"title":"项目管理"},["/docs/MBP/1","/docs/MBP/1.md"]],
  ["v-20f34356","/docs/MBP/2.html",{"title":"范围报告书"},["/docs/MBP/2","/docs/MBP/2.md"]],
  ["v-22a81bf5","/docs/MBP/3.html",{"title":"WBS 工作分解结构表"},["/docs/MBP/3","/docs/MBP/3.md"]],
  ["v-c9c967e6","/docs/MBP/MBP.html",{"title":"项目管理"},["/docs/MBP/MBP","/docs/MBP/MBP.md"]],
  ["v-2bcac60a","/docs/MBP/Project_Scope_Statement.html",{"title":"项目范围说明书"},["/docs/MBP/Project_Scope_Statement","/docs/MBP/Project_Scope_Statement.md"]],
  ["v-fc9ec5c4","/docs/MBP/Requirements_Document.html",{"title":"需求文件"},["/docs/MBP/Requirements_Document","/docs/MBP/Requirements_Document.md"]],
  ["v-3da5ddb4","/docs/MBP/Requirements_Management_Plan.html",{"title":"需求管理计划"},["/docs/MBP/Requirements_Management_Plan","/docs/MBP/Requirements_Management_Plan.md"]],
  ["v-07b3581e","/docs/MBP/Requirements_Traceability_Matrix.html",{"title":"需求跟踪矩阵"},["/docs/MBP/Requirements_Traceability_Matrix","/docs/MBP/Requirements_Traceability_Matrix.md"]],
  ["v-510ab29c","/docs/MBP/mba.html",{"title":"项目管理计划"},["/docs/MBP/mba","/docs/MBP/mba.md"]],
  ["v-9ca3d486","/docs/MBP/project_charte.html",{"title":"项目章程"},["/docs/MBP/project_charte","/docs/MBP/project_charte.md"]],
  ["v-09cd1958","/docs/TP/",{"title":"TP-README"},["/docs/TP/index.html","/docs/TP/README.md"]],
  ["v-3606d5c0","/docs/TP/T-Search.html",{"title":"Search"},["/docs/TP/T-Search","/docs/TP/T-Search.md"]],
  ["v-29df8fc8","/docs/TP/TP00001.html",{"title":"TP00001"},["/docs/TP/TP00001","/docs/TP/TP00001.md"]],
  ["v-0e5dad67","/blogs/Inbox/HT/5.html",{"title":"class 5"},["/blogs/Inbox/HT/5","/blogs/Inbox/HT/5.md"]],
  ["v-10128606","/blogs/Inbox/HT/6.html",{"title":"class 6"},["/blogs/Inbox/HT/6","/blogs/Inbox/HT/6.md"]],
  ["v-11c75ea5","/blogs/Inbox/HT/7.html",{"title":"class 7"},["/blogs/Inbox/HT/7","/blogs/Inbox/HT/7.md"]],
  ["v-137c3744","/blogs/Inbox/HT/8.html",{"title":"class 8"},["/blogs/Inbox/HT/8","/blogs/Inbox/HT/8.md"]],
  ["v-4058ef08","/blogs/Literature%20notes/JP/1.html",{"title":"first note of genki"},["/blogs/Literature notes/JP/1.html","/blogs/Literature%20notes/JP/1","/blogs/Literature notes/JP/1.md","/blogs/Literature%20notes/JP/1.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
